### ISSUE TITLE
Running the jar

### ISSUE THREAD

**Issue by ThijsMaas** [AbeelLab/ctag#1]
Hi,
I would like to run ctag (from the cmd line) but haven't succeeded yet.
The only jar in the repository is ./target/pl-context-1.0-SNAPSHOT-jar.with-dependencies.jar_ if I'm correct and running that as _java -jar .._ gives me 

> Error: Could not find or load main class nl.tudelft.pl2.representation.ui.MainController

So, am I doing this wrong, do I need to compile anything first?
I'm running JRE 1.8.

Thanks,
Thijs

**Comment by thomasabeel** [comment]
Please use the a proper release jar (C-Tag.jar)
https://github.com/AbeelLab/ctag/releases
